{
  "openapi": "3.0.0",
  "info": {
    "title": "API Pix",
    "version": "2.0"
  },
  "servers": [
    {
      "url": "https://trust-pix.santander.com.br/",
      "description": "Produção"
    },
    {
      "url": "https://pix.santander.com.br/api/v1/sandbox/",
      "description": "Sandbox"
    }
  ],
  "tags": [
    {
      "name": "Cob",
      "x-displayName": "Gerenciamento de cobranças para pagamento imediato",
      "description": "Reúne endpoints destinados a lidar com gerenciamento de cobranças imediatas."
    },
    {
      "name": "CobV",
      "x-displayName": "Gerenciamento de cobranças com vencimento",
      "description": "Reúne endpoints destinados a lidar com gerenciamento de cobranças com vencimento."
    },
    {
      "name": "Pix",
      "x-displayName": "Gerenciamento de Pix recebidos",
      "description": "reúne endpoints destinados a lidar com  gerenciamento de Pix recebidos."
    },
    {
      "name": "Webhook",
      "x-displayName": "Gerenciamento de notificações",
      "description": "Reúne endpoints para gerenciamento de notificações por parte do PSP recebedor ao usuário recebedor."
    }
  ],
  "paths": {
    "/cob/{txid}": {
      "put": {
        "tags": [
          "Cob"
        ],
        "summary": "Criar cobrança imediata.",
        "security": [
          {
            "OAuth2": [
              "cob.write"
            ]
          }
        ],
        "description": "Endpoint para criar uma cobrança imediata."
      },
      "patch": {
        "tags": [
          "Cob"
        ],
        "summary": "Revisar cobrança imediata.",
        "security": [
          {
            "OAuth2": [
              "cob.write"
            ]
          }
        ],
        "description": "Endpoint para Alterar ou Cancelar uma cobrança imediata através de um determinado txid."
      },
      "get": {
        "tags": [
          "Cob"
        ],
        "summary": "Consultar cobrança imediata.",
        "security": [
          {
            "OAuth2": [
              "cob.read"
            ]
          }
        ],
        "description": "Endpoint para consultar uma cobrança imediata através de um determinado txid. \n\n\nCobranças com vencimento não devem ser consultadas por este Endpoint. \n\n\nPor se tratar de uma consulta não deve ser enviado \"body\" nesta requisição."
      }
    },
    "/cobv/{txid}": {
      "put": {
        "tags": [
          "CobV"
        ],
        "summary": "Criar cobrança com vencimento.",
        "security": [
          {
            "OAuth2": [
              "cobv.write"
            ]
          }
        ],
        "description": "Endpoint para criar uma cobrança com vencimento."
      },
      "patch": {
        "tags": [
          "CobV"
        ],
        "summary": "Revisar cobrança com vencimento.",
        "security": [
          {
            "OAuth2": [
              "cobv.write"
            ]
          }
        ],
        "description": "Endpoint para Alterar ou Cancelar uma cobrança com vencimento através de um determinado txid."
      },
      "get": {
        "tags": [
          "CobV"
        ],
        "summary": "Consultar cobrança com vencimento.",
        "security": [
          {
            "OAuth2": [
              "cobv.read"
            ]
          }
        ],
        "description": "Endpoint para consultar uma cobrança com vencimento através de um determinado txid. \n\nCobranças imediatas não devem ser consultadas por este Endpoint. \n\nPor se tratar de uma consulta não deve ser enviado \"body\" nesta requisição"
      }
    },
    "/pix": {
      "get": {
        "tags": [
          "Pix"
        ],
        "summary": "Consultar Pix recebidos.",
        "security": [
          {
            "OAuth2": [
              "pix.read"
            ]
          }
        ],
        "description": "Endpoint para Consultar uma lista de Pix Recebidos, contendo liquidação de QRCodes dinâmicos (imediatos/com vencimento), QRCodes Estáticos e/ou transferências (iniciadas por chave pix ou por Banco/Agência/Conta)."
      }
    },
    "/pixrecebidos": {
      "get": {
        "tags": [
          "Pix"
        ],
        "summary": "Consultar lista de Pix recebidos.",
        "description": "Endpoint similar ao serviço padrão do Pix, que permite consultar uma lista de Pix Recebidos, contendo liquidação de QRCodes dinâmicos (imediatos/com vencimento), QRCodes Estáticos e/ou transferências (iniciadas por chave pix ou por Banco/Agência/Conta).\n\nPara cada E2eid, será apresentado o pagador da transação Pix.\n\nPara otimizar a recuperação de grandes volumes de dados na pesquisa, a data inicial e data final devem obrigatoriamente serem iguais.\n",
        "security": [
          {
            "OAuth2": [
              "pix.read"
            ]
          }
        ]
      }
    },
    "/pix/{e2eid}/devolucao/{id}": {
      "put": {
        "tags": [
          "Pix"
        ],
        "summary": "Solicitar devolução.",
        "security": [
          {
            "OAuth2": [
              "pix.write"
            ]
          }
        ],
        "description": "Endpoint para solicitar uma devolução através de um e2eid do Pix e de um ID criado pelo recebedor para nomear unicamente a solicitação da devolução. O motivo que será atribuído à PACS.004 será \"MD06\" ou \"SL02\" de acordo com a aba RTReason da PACS.004 que consta no Catálogo de Mensagens do Pix.\n"
      },
      "get": {
        "tags": [
          "Pix"
        ],
        "summary": "Consultar devolução.",
        "security": [
          {
            "OAuth2": [
              "pix.read"
            ]
          }
        ],
        "description": "Endpoint para consultar uma devolução através de um EndToEndID (e2eid) do Pix e do ID da devolução\n\nPor se tratar de uma consulta não deve ser enviado \"body\" nesta requisição."
      }
    },
    "/webhook/{chave}": {
      "put": {
        "tags": [
          "Webhook"
        ],
        "summary": "Configurar o Webhook Pix.",
        "description": "Endpoint para configuração do serviço de notificações a cerca de Pix recebidos. A idéia é associar uma chave Pix à uma URL que estará apta a tratar a notificação de liquidação de um pix.\n\nSomente Pix associados a um txid serão notificados, por esta regra, transferências não são notificáveis. \n\nComo a relação é uma Chave Pix para uma URL, o mesmo cliente pode usar a mesma URL para chaves diferentes, porém, deve realizar uma chamada para cadastro de  cada chave que dese[...]",
        "security": [
          {
            "OAuth2": [
              "webhook.write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Webhook"
        ],
        "summary": "Exibir informações acerca do Webhook Pix.",
        "description": "Endpoint para recuperação de informações de uma URL Webhook a partir de uma chave Pix.\n\n\nPor se tratar de uma consulta não deve ser enviado \"body\" nesta requisição.\n",
        "security": [
          {
            "OAuth2": [
              "webhook.read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Webhook"
        ],
        "summary": "Cancelar o Webhook Pix.",
        "description": "Endpoint para cancelamento do webhook, ou seja, por este Endpoint será feita a exclusão da associação da chave Pix com uma URL webhook. \n\nO PSP recebedor está livre para remover unilateralmente um webhook que esteja associado a uma chave que não pertence mais a este usuário recebedor.\n",
        "security": [
          {
            "OAuth2": [
              "webhook.write"
            ]
          }
        ]
      }
    },
    "/webhook": {
      "get": {
        "tags": [
          "Webhook"
        ],
        "summary": "Consultar Webhooks cadastrados.",
        "security": [
          {
            "OAuth2": [
              "webhook.read"
            ]
          }
        ],
        "description": "Endpoint para consultar uma lista de URL Webhooks cadastradas. \n\nPor se tratar de uma consulta não deve ser enviado \"body\" nesta requisição.\n"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "/api/v1/oauth",
            "scopes": {
              "cob.write": "Permissão para alteração de cobranças imediatas",
              "cob.read": "Permissão para consulta de cobranças imediatas",
              "cobv.write": "Permissão para alteração de cobranças com vencimento",
              "cobv.read": "Permissão para consulta de cobranças com vencimento",
              "lotecobv.write": "Permissão para alteração de lotes de cobranças com vencimento",
              "lotecobv.read": "Permissão para consulta de lotes de cobranças com vencimento",
              "pix.write": "Permissão para alteração de Pix",
              "pix.read": "Permissão para consulta de Pix",
              "webhook.read": "Permissão para consulta do webhook",
              "webhook.write": "Permissão para alteração do webhook",
              "payloadlocation.write": "Permissão para alteração de payloads",
              "payloadlocation.read": "Permissão para consulta de payloads"
            }
          }
        }
      }
    }
  }
}